repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.83.3
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
      - --hook-config=--path-to-file=README.md
      - --hook-config=--add-to-existing-file=true
